(ns exome.constants)

(def nsssi-terms #{"ESSENTIAL_SPLICE_SITE,3PRIME_UTR","ESSENTIAL_SPLICE_SITE,INTRONIC",
                   "ESSENTIAL_SPLICE_SITE,NON_SYNONYMOUS_CODING",
                   "ESSENTIAL_SPLICE_SITE,SYNONYMOUS_CODING","SPLICE_SITE,STOP_GAINED",
                   "SPLICE_SITE,STOP_LOST","STOP_GAINED","STOP_LOST",
                   "ESSENTIAL_SPLICE_SITE,FRAMESHIFT_CODING","FRAMESHIFT_CODING",
                   "SPLICE_SITE,FRAMESHIFT_CODING","NON_SYNONYMOUS_CODING"})

(def lof-terms #{"ESSENTIAL_SPLICE_SITE,3PRIME_UTR","ESSENTIAL_SPLICE_SITE,INTRONIC",
                 "ESSENTIAL_SPLICE_SITE,NON_SYNONYMOUS_CODING",
                 "ESSENTIAL_SPLICE_SITE,SYNONYMOUS_CODING","SPLICE_SITE,STOP_GAINED",
                 "SPLICE_SITE,STOP_LOST","STOP_GAINED","STOP_LOST",
                 "ESSENTIAL_SPLICE_SITE,FRAMESHIFT_CODING","FRAMESHIFT_CODING",
                 "SPLICE_SITE,FRAMESHIFT_CODING"})
